spring.application.name=clothingstore
server.port=8080
server.servlet.context-path=/api
# spring.datasource.url=jdbc:mysql://localhost:3306/clothing_store_new?createDatabaseIfNotExist=true&serverTimezone=UTC
# spring.datasource.username=root
# spring.datasource.password=Tuankhang412
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
image-upload-path = src/main/resources/static/image


spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB


jwt.secret-key=${JWT_SECRET_KEY:akslfjalskfjalkfjwofijasfamlkfmalf}
jwt.expiration.access-token=${JWT_EXPIRATION_ACCESS_TOKEN:3600000}
jwt.expiration.refresh-token=${JWT_EXPIRATION_REFRESH_TOKEN:86400000}
api-key=${API_KEY:my-secret-api-key-12345}


spring.jpa.open-in-view=false


# tạo màu cho log
spring.output.ansi.enabled=always


springdoc.swagger-ui.doc-expansion=none

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis



# Cấu hình cho ZaloPay
zalopay.app-id=2553
zalopay.key1=PcY4iZIKFCIdgZvA6ueMcMHHUbRLYjPL
zalopay.key2=kLtgPl8HHhfvMuDHPwKfgfsY4Ydm9eIz
zalopay.create-order-url=https://sb-openapi.zalopay.vn/v2/create
zalopay.callback-url=https://sb-openapi.zalopay.vn/v2/query
zalopay.return-url=http://localhost:8080/api/payment/zalo/return

# Cấu hình cho Cloudinary
cdn.cloud-name=dwv3hqktb
cdn.api-key=644745652752952
cdn.api-secret=b_rYnyZeKpVbo8QZPp7tJ2cKi8Y